# Generated by Django 4.2 on 2023-04-28 14:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Rendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_principal', models.FloatField()),
                ('renda_secundaria', models.FloatField(default=0)),
                ('data', models.DateField(default=datetime.datetime(2023, 4, 28, 11, 46, 56, 707866))),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.usuario')),
            ],
            options={
                'verbose_name': 'Renda',
                'verbose_name_plural': 'Rendas',
            },
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.CharField(max_length=80)),
                ('valor', models.FloatField()),
                ('data', models.DateField(default=datetime.datetime(2023, 4, 28, 11, 46, 56, 707866))),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.usuario')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
            },
        ),
    ]
