# Generated by Django 4.2 on 2023-04-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=60)),
                ('rendas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Renda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_principal', models.FloatField()),
                ('renda_secundaria', models.FloatField()),
                ('data', models.DateTimeField()),
                ('usuario_renda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto', models.CharField(max_length=80, verbose_name='Gasto')),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField()),
                ('usuario_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_core.usuario')),
            ],
        ),
    ]
