# Generated by Django 4.2 on 2023-04-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Renda',
            new_name='Rendas',
        ),
        migrations.RenameField(
            model_name='gastos',
            old_name='usuario_gasto',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='rendas',
            old_name='usuario_renda',
            new_name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rendas',
        ),
        migrations.AddField(
            model_name='usuario',
            name='renda',
            field=models.FloatField(null=True),
        ),
    ]
