# Generated by Django 4.1.7 on 2023-04-21 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_alter_gastos_options_alter_rendas_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='ativo',
        ),
    ]
