# Generated by Django 4.2 on 2023-04-21 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_remove_usuario_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 24, 35, 632241)),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='gasto',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
