# Generated by Django 4.2 on 2023-04-21 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_alter_gastos_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 29, 30, 251184)),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 29, 30, 251184)),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='renda_secundaria',
            field=models.FloatField(null=True),
        ),
    ]
