# Generated by Django 4.2 on 2023-04-21 21:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_alter_gastos_data_alter_rendas_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 31, 32, 987534)),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 18, 31, 32, 987534)),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='renda_secundaria',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='renda_total',
            field=models.FloatField(default=0),
        ),
    ]
