# Generated by Django 4.2 on 2023-04-22 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0014_alter_gastos_data_alter_rendas_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 4, 22, 16, 19, 58, 778454, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='rendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 22, 13, 19, 58, 778454)),
        ),
    ]
